#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_I_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_I_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_I_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_I_$(($nF-1)).fasta; done

#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_P_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_P_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_P_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_P_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/ProPIP_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_P_$(($nF-1)).fasta; done

#for nF in {1..4}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_0_5/ProPIPgamma0inferredMSA_r_$nF.fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_1_0/ProPIPgamma1inferredMSA_r_$nF.fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_2_0/ProPIPgamma2inferredMSA_r_$nF.fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/realData_Aligned/aligned_MSA/Gamma/n_4_a_3_0/ProPIPgamma3inferredMSA_r_$nF.fasta; done


#for nF in {0..99}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/wo_cutoff/cluster/ProPIPinferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/wo_cutoff/cluster/ProPIPinferredMSA_I_$nF.fasta; done
#for nF in {0..99}; do mv /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/wo_cutoff/Xubuntu/ProPIPinferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Alignment_Generation/outputs/Alignment_ProPIP/INDELible_Aligned/aligned_MSA/wo_cutoff/Xubuntu/ProPIPinferredMSA_I_$nF.fasta; done

#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_I_$(($nF-1)).fasta; done
#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_P_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Statistics2/real/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/real/ProPIP/Gamma/n_4_a_0_1/ProPIPgamma4inferredMSA_r_$nF.fasta; done


#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_I_$(($nF-1)).fasta; done
for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_0_25/ProPIPk0inferredMSA_r_$nF.fasta; done


#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_I_$(($nF-1)).fasta; done
for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_0_5/ProPIPk1inferredMSA_r_$nF.fasta; done


#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_I_$(($nF-1)).fasta; done
for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_2_0/ProPIPk2inferredMSA_r_$nF.fasta; done

#for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/INDELible/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_I_$(($nF-1)).fasta; done
for nF in {1..100}; do mv /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_I_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/PIPJava/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_P_$(($nF-1)).fasta; done
#for nF in {1..4}; do mv /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_r_$nF.initial.fasta /Users/pouloeld/Documents/Statistics2/real/ProPIP/k_scale/k_3_0/ProPIPk3inferredMSA_r_$nF.fasta; done
