#!/bin/bash
for nF in {1..4};
do
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/MAFFT/mafftInferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/MAFFT/mafftQScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/PRANK/prankInferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/PRANK/prankQScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP/ProPIPinferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP/ProPIPQScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k005/ProPIPk4inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k005/k005QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k010/ProPIPk5inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k010/k010QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k025/ProPIPk0inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k025/k025QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k050/ProPIPk1inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k050/k050QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k2/ProPIPk2inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k2/k2QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kscale/k3/ProPIPk3inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kscale/k3/k3QScore_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_Gamma/Gamma010/ProPIPgamma4inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_Gamma/Gamma010/Gamma010Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_Gamma/Gamma050/ProPIPgamma0inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_Gamma/Gamma050/Gamma050Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_Gamma/Gamma1/ProPIPgamma1inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_Gamma/Gamma1/Gamma1Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_Gamma/Gamma2/ProPIPgamma2inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_Gamma/Gamma2/Gamma2Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_Gamma/Gamma3/ProPIPgamma3inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_Gamma/Gamma3/Gamma3Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kGamma/kg0505/ProPIPkg0inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kGamma/kg0505/kg0505Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kGamma/kg0510/ProPIPkg01inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kGamma/kg0510/kg0510Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kGamma/kg1005/ProPIPkg10inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kGamma/kg1005/kg1005Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_kGamma/kg1010/ProPIPkg11inferredMSA_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_kGamma/kg1010/kg1010Score_r_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/real/True/realData_$nF.fasta -ref /home/eldhose/Desktop/QScore/real/ProPIP_STFT/w128/ProPIP_stft_w_128_r_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/real/ProPIP_STFT/w128/w128Score_r_$nF.txt

done

