#!/bin/bash
for nF in {1..100};
do
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/MAFFT/m_20/mafftInferredMSA_I_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/MAFFT/mafftQScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/PRANK/m_20/prankInferredMSA_I_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/PRANK/prankQScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP/m_20/ProPIPinferredMSA_I_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP/ProPIPQScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k005/ProPIPk4inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k005/k005QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k010/ProPIPk5inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k010/k010QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k025/ProPIPk0inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k025/k025QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k050/ProPIPk1inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k050/k050QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k2/ProPIPk2inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k2/k2QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k3/ProPIPk3inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k3/k3QScore_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma010/ProPIPgamma4inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma010/Gamma010Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma050/ProPIPgamma0inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma050/Gamma050Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma1/ProPIPgamma1inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma1/Gamma1Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma2/ProPIPgamma2inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma2/Gamma2Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma3/ProPIPgamma3inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma3/Gamma3Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg0505/ProPIPkg0inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg0505/kg0505Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg0510/ProPIPkg01inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg0510/kg0510Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg1005/ProPIPkg10inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg1005/kg1005Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg1010/ProPIPkg11inferredMSA_I_$(($nF-1)).fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg1010/kg1010Score_$nF.txt
	/home/eldhose/Desktop/QScore/qscore  -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/True/m_20/out_$(($nF-1))_TRUE_1.fasta -ref /home/eldhose/Desktop/QScore/INDELible/ProPIP_STFT/w128/ProPIP_stft_w_128_MSA_I_$nF.fasta > /home/eldhose/Desktop/QScore/QScore/INDELible/ProPIP_STFT/w128/w128Score_$nF.txt

done

