#!/bin/bash

/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/MAFFT/m_20/mafftInferredMSA_I_1.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/MAFFT/mafftQScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/PRANK/m_20/prankInferredMSA_I_1.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/PRANK/prankQScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP/m_20/ProPIPinferredMSA_I_1.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP/ProPIPQScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k005/ProPIPk4inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k005/k005QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k010/ProPIPk5inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k010/k010QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k025/ProPIPk0inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k025/k025QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k050/ProPIPk1inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k050/k050QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k2/ProPIPk2inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k2/k2QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kscale/k3/ProPIPk3inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kscale/k3/k3QScore_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma010/ProPIPgamma4inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma010/Gamma010Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma050/ProPIPgamma0inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma050/Gamma050Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma1/ProPIPgamma1inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma1/Gamma1Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma2/ProPIPgamma2inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma2/Gamma2Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma3/ProPIPgamma3inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_Gamma/Gamma3/Gamma3Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kGamma/kg0505/ProPIPkg0inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg0505/kg0505Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kGamma/kg0510/ProPIPkg01inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg0510/kg0510Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kGamma/kg1005/ProPIPkg10inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg1005/kg1005Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_kGamma/kg1010/ProPIPkg11inferredMSA_I_0.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_kGamma/kg1010/kg1010Score_1.txt
/Users/pouloeld/Desktop/QScore/qscore  -modeler -cline -test /Users/pouloeld/Desktop/QScore/INDELible/True/m_20/out_0_TRUE_1.fasta -ref /Users/pouloeld/Desktop/QScore/INDELible/ProPIP_STFT/w128/ProPIP_stft_w_128_MSA_I_1.fasta > /Users/pouloeld/Desktop/QScore/QScore/INDELible/ProPIP_STFT/w128/w128Score_1.txt



