#!/bin/bash
for nF in {1..100};
do
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/MAFFT/mafftInferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/MAFFT/MAFFT$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/PRANK/prankInferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/PRANK/PRANK$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP/ProPIPinferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP/ProPIP$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma010/ProPIPgamma4inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_Gamma/Gamma010/g010$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma050/ProPIPgamma0inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_Gamma/Gamma050/g050$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma1/ProPIPgamma1inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_Gamma/Gamma1/g1$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma2/ProPIPgamma2inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_Gamma/Gamma2/g2$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_Gamma/Gamma3/ProPIPgamma3inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_Gamma/Gamma3/g3$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k005/ProPIPk4inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k005/k005$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k010/ProPIPk5inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k010/k010$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k025/ProPIPk0inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k025/k025$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k050/ProPIPk1inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k050/k050$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k2/ProPIPk2inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k2/k2$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kscale/k3/ProPIPk3inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kscale/k3/k3$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg0505/ProPIPkg0inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kGamma/kg0505/kg0505$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg0510/ProPIPkg01inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kGamma/kg0510/kg0510$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg1005/ProPIPkg10inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kGamma/kg1005/kg1005$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_kGamma/kg1010/ProPIPkg11inferredMSA_I_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_kGamma/kg1010/kg1010$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/ProPIP_STFT/w_128/ProPIP_stft_w_128_MSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/ProPIP_STFT/w_128/w128$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/SBDP/T_1/ProPIPSB1inferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/SBDP/T_1/SBT1$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/SBDP/T_3/ProPIPSB3inferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/SBDP/T_3/SBT3$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/SBDP/T_5/ProPIPSB5inferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/SBDP/T_5/SBT5$nF.txt
/home/eldhose/Desktop/QScore/binQscore -modeler -cline -test /home/eldhose/Desktop/QScore/INDELible/SBDP/T_10/ProPIPSB10inferredMSA_I_$nF.fasta -ref /home/eldhose/Desktop/QScore/INDELible/True/out_$(($nF-1))_TRUE_1.fasta > /home/eldhose/Desktop/QScore/QOut/SBDP/T_10/SBT10$nF.txt
done
