#!/bin/bash
for nF in {1..100};
do
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test home/eldhose/Desktop/QScore/PIPJava/MAFFT/mafftInferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/MAFFT/mafftQScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/PRANK/prankInferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/PRANK/prankQScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP/ProPIPinferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP/ProPIPQScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k005/ProPIPk4inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k005/k005QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k010/ProPIPk5inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k010/k010QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k025/ProPIPk0inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k025/k025QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k050/ProPIPk1inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k050/k050QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k2/ProPIPk2inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k2/k2QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kscale/k3/ProPIPk3inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kscale/k3/k3QScore_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_Gamma/Gamma010/ProPIPgamma4inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_Gamma/Gamma010/Gamma010Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_Gamma/Gamma050/ProPIPgamma0inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_Gamma/Gamma050/Gamma050Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_Gamma/Gamma1/ProPIPgamma1inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_Gamma/Gamma1/Gamma1Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_Gamma/Gamma2/ProPIPgamma2inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_Gamma/Gamma2/Gamma2Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_Gamma/Gamma3/ProPIPgamma3inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_Gamma/Gamma3/Gamma3Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kGamma/kg0505/ProPIPkg0inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kGamma/kg0505/kg0505Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kGamma/kg0510/ProPIPkg01inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kGamma/kg0510/kg0510Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kGamma/kg1005/ProPIPkg10inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kGamma/kg1005/kg1005Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_kGamma/kg1010/ProPIPkg11inferredMSA_P_$(($nF-1)).fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_kGamma/kg1010/kg1010Score_P_$nF.txt
	/home/eldhose/Desktop/QScore/binQScore  -modeler -cline -test /home/eldhose/Desktop/QScore/PIPJava/ProPIP_STFT/w128/ProPIP_stft_w_128_MSA_P_$nF.fasta -ref /home/eldhose/Desktop/QScore/PIPJava/True/sim-$(($nF-1))_MSA.fasta > /home/eldhose/Desktop/QScore/QScore/PIPJava/ProPIP_STFT/w128/w128Score_P_$nF.txt

done

